from processors.simple_gpt4_processor import SimpleGPT4Processor
from processors.base_4o_mini import Base4oMiniProcessor
from processors.few_shot_gpt4_processor import FewShotGPT4Processor
from processors.base_processor import BaseLLMProcessor