from processors.simple_gpt4_processor import SimpleGPT4Processor
from processors.context_gpt35_processor import ContextGPT35Processor
from processors.few_shot_gpt4_processor import FewShotGPT4Processor
from processors.base_processor import BaseLLMProcessor